repos:
  - repo: local
    hooks:
      - id: autopep8
        name: autopep8 (module)
        entry: python -m autopep8
        language: system
        types: [python]
        args: [--in-place, --aggressive, --end-with-newline, --select, "W291,W293"]
